declare module 'bpmn-js-color-picker';
declare module 'bpmn-js-embedded-comments';
declare module 'bpmn-js-properties-panel';
declare module 'bpmn-js-properties-panel/*';
declare module 'bpmn-js-task-resize';
declare module 'bpmn-js-task-resize/lib';
// declare module 'dmn-js/lib/*';
declare module 'dmn-js-properties-panel';
declare module 'dmn-js-properties-panel/*';
declare module 'diagram-js-minimap';
declare module '@bpmn-io/add-exporter';
